### ISSUE TITLE
missing prefabs... .meta files missing?

### ISSUE THREAD

**Issue by agardony** [FlipWebApps/HololensGPS#2]
Hi I wanted to test out this project but when I load it into Unity I see several missing prefabs. This link suggests it might be due to missing .meta files in the repo. 

https://answers.unity.com/questions/278326/missing-prefab.html

**Comment by FlipWebApps** [comment]
Hi. What version of Unity did you try with? I know this was very sensitive to different versions, mostly relating to the holotoolkit so that so might give problems on anything other than the version I used 2017.1.1f1

**Comment by Mkohm** [comment]
.meta files is added to your .gitignore. This is probably the cause of these troubles.

**Comment by Mkohm** [comment]
Im trying to run this project as well, but have to add scripts to all of the components to get it running.

**Comment by Mkohm** [comment]
If you cold say where the scripts shold be located it would help a ton @agardony :)

**Comment by dudepants** [comment]
I'm having the same issue with missing prefabs. As for the scripts, I'm GUESSING it's the two mono scripts that are at the top level in Assets. So, EventProcessor and GPS_Receiver.

**Comment by FlipWebApps** [comment]
Well spotted @Mkohm. Was a generic .net .gitignore I had copied from another project which is why that sneaked in.

I have updated the .gitignore and all the .meta files should be there now. Note though that I haven't touched this project for a long time, so make no promises to how well it will work. It should be fine in the version of Unity that it was created with, but I know they have changed the HoloToolkit (MixedRealityToolkit) a lot since this was created.
